### ISSUE TITLE
crypto_aead _NPUBBYTES vs. _NONCEBYTES

### ISSUE THREAD

**Issue by jvarho** [stef/pysodium#80]
The constant added in #78 is crypto_aead_xchacha20poly1305_ietf_NPUBBYTES while the other AEAD variants have _NONCEBYTES. It would be nice if they were consistent. Maybe either rename the new one to be consistent or add _NPUBBYTES copies (to avoid breakage) of the old ones since that is what libsodium uses?

**Comment by stef** [comment]
indeed, it seems: https://github.com/jedisct1/libsodium/search?utf8=%E2%9C%93&q=crypto_aead_xchacha20poly1305_ietf_NPUBBYTES&type=

@robehickman can you tell us something about this?

**Comment by robehickman** [comment]
I copied the constant from the sodium documentation:

https://download.libsodium.org/doc/secret-key_cryptography/xchacha20-poly1305_construction.html

**Comment by jedisct1** [comment]
Stream ciphers use `NONCEBYTES`, whereas AEAD constructions use `NPUBBYTES`. In the CAESAR competition, optional support for a "secret" nonce was specified. Hence the distinction between a "public" and a "secret" nonce. In practice, this specification had little success, because the use cases were pretty limited.
Still, this is something that can easily be added later if needed.

**Comment by robehickman** [comment]
@jedisct1 Out of personal interest, where would a secret nonce be used?

**Comment by jedisct1** [comment]
Lamport signatures and hierarchical encryption.

**Comment by robehickman** [comment]
Interesting, thanks.

**Comment by stef** [comment]
so i'm a bit confused, what is the right thing to do here to be as close as possible to libsodium?

**Comment by jedisct1** [comment]
I would suggest using `NPUBBYTES` for the AEAD constructions, and `NONCEBYTES` for the rest, like the original API.
