### ISSUE TITLE
PyPi version number not compliant with PEP 0440?

### ISSUE THREAD

**Issue by mans0954** [stef/pysodium#85]
Hello,

The PyPi package has version `0.7.0_0`, whereas this GitHub repository has version `0.7.0`. Reading [https://www.python.org/dev/peps/pep-0440/], I'm not convinced that this is a valid version. It says _ can be used as a separator for pre, post, dev and local releases, but the implication seems to be that there should be at least one alphabetic character before the number. In particular, using the `VERSION_PATTERN` regexp in Appendix B does not produce a match for `0.7.0_0`.

(I realise this may sound a bit like mindless pedantry, but I have a reason for asking. I'm the Uploader for the Debian package of pysodium, and the upstream version is used to detect when there is a new upstream release, and to form the Debian version for the package.)

Thanks.

Christopher

**Comment by mans0954** [comment]
I've just tried building the package and get the warning:
```
/usr/lib/python3/dist-packages/setuptools/dist.py:364: UserWarning: The version specified ('0.7.0_0') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```

**Comment by stef** [comment]
hey,  thanks ;)

yeah, it was a workaround, to be able to upload a corrected version to pypi. and pypi is so stupid it does not allow to delete and then upload a file with the same version. you can safely say it is 0.7.0, as it is also in the git repo still as such. will hopefully not happen next time. (the reason for reuploading to pypi was to actually publish a gpg signed version, instead of an unsigned one)

sorry for the troubles.

**Comment by stef** [comment]
and thanks a lot for packaging this for debian! <3

**Comment by mans0954** [comment]
Thanks. Debian likes it when developers gpg sign their packages :)
